CONSUMER_KEY: "OsuOzkWeTgSmweKZ07uGF1GGm"
CONSUMER_SECRET: "e24zvacHX0EuGuJtxblhvpPdBXyy0JzESQqN3niXyAnZVHqBag"
ACCESS_TOKEN: "354442110-kO801M3Ng1qajgaA04Ob1X8nqOATHU3JbkLxKIoz"
ACCESS_SECRET: "jfvmyGQQ8ApAewLlI5oo5GwUcpqawIh243T6tAstJ6Hro"

MONGODB_HOST: "mongodb://139.5.147.170:27017/"
MONGODB_DB: "wm-wordcloud-infamwetrust"

FILTER_KEYWORD: "\u0E40\u0E25\u0E37\u0E2D\u0E14\u0E02\u0E49\u0E19\u0E04\u0E19\u0E08\u0E32\u0E07"
FILTER_LANG: th

LAST: 50000